# Project identification
sonar.projectKey=anshikababel_olms-project
sonar.organization=anshikababel

# Source code location
sonar.sources=.

# Optional but useful (exclude unnecessary folders)
sonar.exclusions=node_modules/**, public/**

# SonarCloud server URL
sonar.host.url=https://sonarcloud.io

# Authentication token
sonar.token=b905b6368667563ff221d4f17cbd580a7e13eacd

# (Optional) Ignore SCM warning
sonar.scm.provider=git
